import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Cornell University Beta Theta Pi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/btp_icon.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Link href={"/"}>
            <Image
              src="/btp_icon.png"
              alt="Beta Logo"
              className={styles.vercelLogo}
              width={36}
              height={36}
              priority
            />
          </Link>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/ross.jpeg"
            alt="Big hawaiian man"
            width={450}
            height={450}
            priority
          />
        </div>
        <div>
          <h3>Roosevelt Lu, Brother #2073.</h3>
          <p className={styles.ross}>
            Roosevelt Lu is a senior at Cornell University, where he is majoring
            in pre-med with the goal of becoming a doctor. Throughout his time
            at Cornell, Roosevelt has distinguished himself as a hardworking and
            dedicated student, consistently earning top grades in his classes.
            In addition to his academic pursuits, Roosevelt is also an avid
            basketball player and can often be found practicing his skills on
            the court. He is a talented athlete and has even considered joining
            the university's basketball team.
            <br></br>
            <br></br>
            Aside from his love of basketball, Roosevelt is also passionate
            about music and enjoys listening to a variety of genres in his free
            time. He has even considered joining a music club on campus to share
            his love of music with others. Roosevelt is also an avid reader and
            can often be found with his nose buried in a book when he has some
            downtime. He enjoys reading works from a variety of authors and
            genres, and often participates in book clubs and discussions with
            his friends.
            <br></br>
            <br></br>
            In his spare time, Roosevelt also volunteers at a local hospital,
            where he helps out in various departments and gains valuable
            experience in the medical field. He is passionate about giving back
            to his community and is always looking for ways to make a positive
            impact. In addition to his volunteering efforts at the hospital,
            Roosevelt is also involved in various community service projects,
            such as beach cleanups and food drives.
            <br></br>
            <br></br>
            When he's not busy with schoolwork, extracurricular activities, or
            volunteering, Roosevelt enjoys spending time with his family. He has
            a close-knit group of relatives who he loves to visit and spend time
            with, especially during the holidays. Roosevelt is also a sociable
            person and enjoys spending time with his peers, whether it's
            studying together or simply hanging out.
            <br></br>
            <br></br>
            Despite the demanding schedule of a pre-med student, Roosevelt
            always makes time for the things he loves and is determined to
            succeed in both his personal and professional endeavors. He is a
            driven and motivated individual who is passionate about helping
            others and making a difference in the world. With his strong work
            ethic and dedication to his studies, Roosevelt is well on his way to
            achieving his dream of becoming a doctor and making a positive
            impact in the lives of others.
            <br></br>
            Support Ross on his journey by suscribing to him at OnlyFans here:
            penisland.com.
          </p>
        </div>
      </main>
    </>
  );
}
